// flow-typed signature: b8e41e146648a109d6ab8dca14f4f0bf
// flow-typed version: <<STUB>>/jsplumb_v2.2.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsplumb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsplumb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsplumb/build-support' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/animation/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/chart/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/demo-list' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/draggableConnectors/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/dynamicAnchors/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/flowchart/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/groups/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/lists/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/perimeterAnchors/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/sourcesAndTargets/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/statemachine/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/webpack/Gruntfile' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/webpack/index' {
  declare module.exports: any;
}

declare module 'jsplumb/demo/webpack/webpack.config' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/apidocs/api' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/apidocs/assets/js/api-filter' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/apidocs/assets/js/api-list' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/apidocs/assets/js/api-search' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/apidocs/assets/js/apidocs' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/apidocs/assets/js/yui-prettify' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/apidocs/assets/vendor/prettify/prettify-min' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/demo/animation/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/demo/chart/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/demo/draggableConnectors/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/demo/dynamicAnchors/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/demo/flowchart/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/demo/groups/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/demo/perimeterAnchors/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/demo/sourcesAndTargets/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/demo/statemachine/demo' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/js/demo-list' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/js/jsPlumb-2.2.0-min' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/js/jsPlumb-2.2.0' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/test-apidocs/api' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/test-apidocs/assets/js/api-filter' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/test-apidocs/assets/js/api-list' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/test-apidocs/assets/js/api-search' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/test-apidocs/assets/js/apidocs' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/test-apidocs/assets/js/yui-prettify' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/test-apidocs/assets/vendor/prettify/prettify-min' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/tests/bind-shim' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/tests/endpoint-loadtest' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/tests/jsPlumb-tests' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/tests/loadtest' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/tests/makeSourceLoadTest' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/tests/qunit-1.11.0' {
  declare module.exports: any;
}

declare module 'jsplumb/dist/tests/test-support-dom' {
  declare module.exports: any;
}

declare module 'jsplumb/doc/api/anchors' {
  declare module.exports: any;
}

declare module 'jsplumb/doc/api/connection-api' {
  declare module.exports: any;
}

declare module 'jsplumb/doc/api/connectors' {
  declare module.exports: any;
}

declare module 'jsplumb/doc/api/endpoint-api' {
  declare module.exports: any;
}

declare module 'jsplumb/doc/api/jsplumb-api' {
  declare module.exports: any;
}

declare module 'jsplumb/doc/api/overlaycomponent' {
  declare module.exports: any;
}

declare module 'jsplumb/doc/api/overlays-api' {
  declare module.exports: any;
}

declare module 'jsplumb/doc/api/uicomponent' {
  declare module.exports: any;
}

declare module 'jsplumb/doc/api/util-api' {
  declare module.exports: any;
}

declare module 'jsplumb/Gruntfile' {
  declare module.exports: any;
}

declare module 'jsplumb/jekyll/test-apidocs/api' {
  declare module.exports: any;
}

declare module 'jsplumb/jekyll/test-apidocs/assets/js/api-filter' {
  declare module.exports: any;
}

declare module 'jsplumb/jekyll/test-apidocs/assets/js/api-list' {
  declare module.exports: any;
}

declare module 'jsplumb/jekyll/test-apidocs/assets/js/api-search' {
  declare module.exports: any;
}

declare module 'jsplumb/jekyll/test-apidocs/assets/js/apidocs' {
  declare module.exports: any;
}

declare module 'jsplumb/jekyll/test-apidocs/assets/js/yui-prettify' {
  declare module.exports: any;
}

declare module 'jsplumb/jekyll/test-apidocs/assets/vendor/prettify/prettify-min' {
  declare module.exports: any;
}

declare module 'jsplumb/jekyll/yuitheme/helpers' {
  declare module.exports: any;
}

declare module 'jsplumb/lib/biltong-0.3' {
  declare module.exports: any;
}

declare module 'jsplumb/lib/jsBezier-0.8' {
  declare module.exports: any;
}

declare module 'jsplumb/lib/katavorio-0.17.0' {
  declare module.exports: any;
}

declare module 'jsplumb/lib/mottle-0.7.3' {
  declare module.exports: any;
}

declare module 'jsplumb/src/anchors' {
  declare module.exports: any;
}

declare module 'jsplumb/src/base-library-adapter' {
  declare module.exports: any;
}

declare module 'jsplumb/src/bezier-editor' {
  declare module.exports: any;
}

declare module 'jsplumb/src/browser-util' {
  declare module.exports: any;
}

declare module 'jsplumb/src/connection' {
  declare module.exports: any;
}

declare module 'jsplumb/src/connectors-bezier' {
  declare module.exports: any;
}

declare module 'jsplumb/src/connectors-flowchart' {
  declare module.exports: any;
}

declare module 'jsplumb/src/connectors-statemachine' {
  declare module.exports: any;
}

declare module 'jsplumb/src/connectors-straight' {
  declare module.exports: any;
}

declare module 'jsplumb/src/defaults' {
  declare module.exports: any;
}

declare module 'jsplumb/src/dom-adapter' {
  declare module.exports: any;
}

declare module 'jsplumb/src/dom.jsPlumb' {
  declare module.exports: any;
}

declare module 'jsplumb/src/endpoint' {
  declare module.exports: any;
}

declare module 'jsplumb/src/group' {
  declare module.exports: any;
}

declare module 'jsplumb/src/jsPlumb' {
  declare module.exports: any;
}

declare module 'jsplumb/src/overlay-component' {
  declare module.exports: any;
}

declare module 'jsplumb/src/renderers-svg' {
  declare module.exports: any;
}

declare module 'jsplumb/src/util' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/bind-shim' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/endpoint-loadtest' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/experiments/connector-editors' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/experiments/npm/browserify-test' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/experiments/npm/input' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/experiments/overlays-guidelines' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/jsPlumb-tests' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/loadtest' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/makeSourceLoadTest' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/miscellaneous/exampleConnector' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/miscellaneous/issue_106_test/js/EndPoints' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/miscellaneous/issue_106_test/js/jquery-ui-1.8.14.custom.min' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/miscellaneous/issue_106_test/js/jquery.jsPlumb-1.3.1-all' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/miscellaneous/issue_106_test/js/jquery.min' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/miscellaneous/issue_106_test/js/util' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/miscellaneous/jquery.mockjax' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/miscellaneous/jQueryOffsetCSS3Scale' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/miscellaneous/object-avoid' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/miscellaneous/sprout-test' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/miscellaneous/svg-sprout' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/qunit-1.11.0' {
  declare module.exports: any;
}

declare module 'jsplumb/tests/test-support-dom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsplumb/build-support.js' {
  declare module.exports: $Exports<'jsplumb/build-support'>;
}
declare module 'jsplumb/demo/animation/demo.js' {
  declare module.exports: $Exports<'jsplumb/demo/animation/demo'>;
}
declare module 'jsplumb/demo/chart/demo.js' {
  declare module.exports: $Exports<'jsplumb/demo/chart/demo'>;
}
declare module 'jsplumb/demo/demo-list.js' {
  declare module.exports: $Exports<'jsplumb/demo/demo-list'>;
}
declare module 'jsplumb/demo/draggableConnectors/demo.js' {
  declare module.exports: $Exports<'jsplumb/demo/draggableConnectors/demo'>;
}
declare module 'jsplumb/demo/dynamicAnchors/demo.js' {
  declare module.exports: $Exports<'jsplumb/demo/dynamicAnchors/demo'>;
}
declare module 'jsplumb/demo/flowchart/demo.js' {
  declare module.exports: $Exports<'jsplumb/demo/flowchart/demo'>;
}
declare module 'jsplumb/demo/groups/demo.js' {
  declare module.exports: $Exports<'jsplumb/demo/groups/demo'>;
}
declare module 'jsplumb/demo/lists/demo.js' {
  declare module.exports: $Exports<'jsplumb/demo/lists/demo'>;
}
declare module 'jsplumb/demo/perimeterAnchors/demo.js' {
  declare module.exports: $Exports<'jsplumb/demo/perimeterAnchors/demo'>;
}
declare module 'jsplumb/demo/sourcesAndTargets/demo.js' {
  declare module.exports: $Exports<'jsplumb/demo/sourcesAndTargets/demo'>;
}
declare module 'jsplumb/demo/statemachine/demo.js' {
  declare module.exports: $Exports<'jsplumb/demo/statemachine/demo'>;
}
declare module 'jsplumb/demo/webpack/Gruntfile.js' {
  declare module.exports: $Exports<'jsplumb/demo/webpack/Gruntfile'>;
}
declare module 'jsplumb/demo/webpack/index.js' {
  declare module.exports: $Exports<'jsplumb/demo/webpack/index'>;
}
declare module 'jsplumb/demo/webpack/webpack.config.js' {
  declare module.exports: $Exports<'jsplumb/demo/webpack/webpack.config'>;
}
declare module 'jsplumb/dist/apidocs/api.js' {
  declare module.exports: $Exports<'jsplumb/dist/apidocs/api'>;
}
declare module 'jsplumb/dist/apidocs/assets/js/api-filter.js' {
  declare module.exports: $Exports<'jsplumb/dist/apidocs/assets/js/api-filter'>;
}
declare module 'jsplumb/dist/apidocs/assets/js/api-list.js' {
  declare module.exports: $Exports<'jsplumb/dist/apidocs/assets/js/api-list'>;
}
declare module 'jsplumb/dist/apidocs/assets/js/api-search.js' {
  declare module.exports: $Exports<'jsplumb/dist/apidocs/assets/js/api-search'>;
}
declare module 'jsplumb/dist/apidocs/assets/js/apidocs.js' {
  declare module.exports: $Exports<'jsplumb/dist/apidocs/assets/js/apidocs'>;
}
declare module 'jsplumb/dist/apidocs/assets/js/yui-prettify.js' {
  declare module.exports: $Exports<'jsplumb/dist/apidocs/assets/js/yui-prettify'>;
}
declare module 'jsplumb/dist/apidocs/assets/vendor/prettify/prettify-min.js' {
  declare module.exports: $Exports<'jsplumb/dist/apidocs/assets/vendor/prettify/prettify-min'>;
}
declare module 'jsplumb/dist/demo/animation/demo.js' {
  declare module.exports: $Exports<'jsplumb/dist/demo/animation/demo'>;
}
declare module 'jsplumb/dist/demo/chart/demo.js' {
  declare module.exports: $Exports<'jsplumb/dist/demo/chart/demo'>;
}
declare module 'jsplumb/dist/demo/draggableConnectors/demo.js' {
  declare module.exports: $Exports<'jsplumb/dist/demo/draggableConnectors/demo'>;
}
declare module 'jsplumb/dist/demo/dynamicAnchors/demo.js' {
  declare module.exports: $Exports<'jsplumb/dist/demo/dynamicAnchors/demo'>;
}
declare module 'jsplumb/dist/demo/flowchart/demo.js' {
  declare module.exports: $Exports<'jsplumb/dist/demo/flowchart/demo'>;
}
declare module 'jsplumb/dist/demo/groups/demo.js' {
  declare module.exports: $Exports<'jsplumb/dist/demo/groups/demo'>;
}
declare module 'jsplumb/dist/demo/perimeterAnchors/demo.js' {
  declare module.exports: $Exports<'jsplumb/dist/demo/perimeterAnchors/demo'>;
}
declare module 'jsplumb/dist/demo/sourcesAndTargets/demo.js' {
  declare module.exports: $Exports<'jsplumb/dist/demo/sourcesAndTargets/demo'>;
}
declare module 'jsplumb/dist/demo/statemachine/demo.js' {
  declare module.exports: $Exports<'jsplumb/dist/demo/statemachine/demo'>;
}
declare module 'jsplumb/dist/js/demo-list.js' {
  declare module.exports: $Exports<'jsplumb/dist/js/demo-list'>;
}
declare module 'jsplumb/dist/js/jsPlumb-2.2.0-min.js' {
  declare module.exports: $Exports<'jsplumb/dist/js/jsPlumb-2.2.0-min'>;
}
declare module 'jsplumb/dist/js/jsPlumb-2.2.0.js' {
  declare module.exports: $Exports<'jsplumb/dist/js/jsPlumb-2.2.0'>;
}
declare module 'jsplumb/dist/test-apidocs/api.js' {
  declare module.exports: $Exports<'jsplumb/dist/test-apidocs/api'>;
}
declare module 'jsplumb/dist/test-apidocs/assets/js/api-filter.js' {
  declare module.exports: $Exports<'jsplumb/dist/test-apidocs/assets/js/api-filter'>;
}
declare module 'jsplumb/dist/test-apidocs/assets/js/api-list.js' {
  declare module.exports: $Exports<'jsplumb/dist/test-apidocs/assets/js/api-list'>;
}
declare module 'jsplumb/dist/test-apidocs/assets/js/api-search.js' {
  declare module.exports: $Exports<'jsplumb/dist/test-apidocs/assets/js/api-search'>;
}
declare module 'jsplumb/dist/test-apidocs/assets/js/apidocs.js' {
  declare module.exports: $Exports<'jsplumb/dist/test-apidocs/assets/js/apidocs'>;
}
declare module 'jsplumb/dist/test-apidocs/assets/js/yui-prettify.js' {
  declare module.exports: $Exports<'jsplumb/dist/test-apidocs/assets/js/yui-prettify'>;
}
declare module 'jsplumb/dist/test-apidocs/assets/vendor/prettify/prettify-min.js' {
  declare module.exports: $Exports<'jsplumb/dist/test-apidocs/assets/vendor/prettify/prettify-min'>;
}
declare module 'jsplumb/dist/tests/bind-shim.js' {
  declare module.exports: $Exports<'jsplumb/dist/tests/bind-shim'>;
}
declare module 'jsplumb/dist/tests/endpoint-loadtest.js' {
  declare module.exports: $Exports<'jsplumb/dist/tests/endpoint-loadtest'>;
}
declare module 'jsplumb/dist/tests/jsPlumb-tests.js' {
  declare module.exports: $Exports<'jsplumb/dist/tests/jsPlumb-tests'>;
}
declare module 'jsplumb/dist/tests/loadtest.js' {
  declare module.exports: $Exports<'jsplumb/dist/tests/loadtest'>;
}
declare module 'jsplumb/dist/tests/makeSourceLoadTest.js' {
  declare module.exports: $Exports<'jsplumb/dist/tests/makeSourceLoadTest'>;
}
declare module 'jsplumb/dist/tests/qunit-1.11.0.js' {
  declare module.exports: $Exports<'jsplumb/dist/tests/qunit-1.11.0'>;
}
declare module 'jsplumb/dist/tests/test-support-dom.js' {
  declare module.exports: $Exports<'jsplumb/dist/tests/test-support-dom'>;
}
declare module 'jsplumb/doc/api/anchors.js' {
  declare module.exports: $Exports<'jsplumb/doc/api/anchors'>;
}
declare module 'jsplumb/doc/api/connection-api.js' {
  declare module.exports: $Exports<'jsplumb/doc/api/connection-api'>;
}
declare module 'jsplumb/doc/api/connectors.js' {
  declare module.exports: $Exports<'jsplumb/doc/api/connectors'>;
}
declare module 'jsplumb/doc/api/endpoint-api.js' {
  declare module.exports: $Exports<'jsplumb/doc/api/endpoint-api'>;
}
declare module 'jsplumb/doc/api/jsplumb-api.js' {
  declare module.exports: $Exports<'jsplumb/doc/api/jsplumb-api'>;
}
declare module 'jsplumb/doc/api/overlaycomponent.js' {
  declare module.exports: $Exports<'jsplumb/doc/api/overlaycomponent'>;
}
declare module 'jsplumb/doc/api/overlays-api.js' {
  declare module.exports: $Exports<'jsplumb/doc/api/overlays-api'>;
}
declare module 'jsplumb/doc/api/uicomponent.js' {
  declare module.exports: $Exports<'jsplumb/doc/api/uicomponent'>;
}
declare module 'jsplumb/doc/api/util-api.js' {
  declare module.exports: $Exports<'jsplumb/doc/api/util-api'>;
}
declare module 'jsplumb/Gruntfile.js' {
  declare module.exports: $Exports<'jsplumb/Gruntfile'>;
}
declare module 'jsplumb/jekyll/test-apidocs/api.js' {
  declare module.exports: $Exports<'jsplumb/jekyll/test-apidocs/api'>;
}
declare module 'jsplumb/jekyll/test-apidocs/assets/js/api-filter.js' {
  declare module.exports: $Exports<'jsplumb/jekyll/test-apidocs/assets/js/api-filter'>;
}
declare module 'jsplumb/jekyll/test-apidocs/assets/js/api-list.js' {
  declare module.exports: $Exports<'jsplumb/jekyll/test-apidocs/assets/js/api-list'>;
}
declare module 'jsplumb/jekyll/test-apidocs/assets/js/api-search.js' {
  declare module.exports: $Exports<'jsplumb/jekyll/test-apidocs/assets/js/api-search'>;
}
declare module 'jsplumb/jekyll/test-apidocs/assets/js/apidocs.js' {
  declare module.exports: $Exports<'jsplumb/jekyll/test-apidocs/assets/js/apidocs'>;
}
declare module 'jsplumb/jekyll/test-apidocs/assets/js/yui-prettify.js' {
  declare module.exports: $Exports<'jsplumb/jekyll/test-apidocs/assets/js/yui-prettify'>;
}
declare module 'jsplumb/jekyll/test-apidocs/assets/vendor/prettify/prettify-min.js' {
  declare module.exports: $Exports<'jsplumb/jekyll/test-apidocs/assets/vendor/prettify/prettify-min'>;
}
declare module 'jsplumb/jekyll/yuitheme/helpers.js' {
  declare module.exports: $Exports<'jsplumb/jekyll/yuitheme/helpers'>;
}
declare module 'jsplumb/lib/biltong-0.3.js' {
  declare module.exports: $Exports<'jsplumb/lib/biltong-0.3'>;
}
declare module 'jsplumb/lib/jsBezier-0.8.js' {
  declare module.exports: $Exports<'jsplumb/lib/jsBezier-0.8'>;
}
declare module 'jsplumb/lib/katavorio-0.17.0.js' {
  declare module.exports: $Exports<'jsplumb/lib/katavorio-0.17.0'>;
}
declare module 'jsplumb/lib/mottle-0.7.3.js' {
  declare module.exports: $Exports<'jsplumb/lib/mottle-0.7.3'>;
}
declare module 'jsplumb/src/anchors.js' {
  declare module.exports: $Exports<'jsplumb/src/anchors'>;
}
declare module 'jsplumb/src/base-library-adapter.js' {
  declare module.exports: $Exports<'jsplumb/src/base-library-adapter'>;
}
declare module 'jsplumb/src/bezier-editor.js' {
  declare module.exports: $Exports<'jsplumb/src/bezier-editor'>;
}
declare module 'jsplumb/src/browser-util.js' {
  declare module.exports: $Exports<'jsplumb/src/browser-util'>;
}
declare module 'jsplumb/src/connection.js' {
  declare module.exports: $Exports<'jsplumb/src/connection'>;
}
declare module 'jsplumb/src/connectors-bezier.js' {
  declare module.exports: $Exports<'jsplumb/src/connectors-bezier'>;
}
declare module 'jsplumb/src/connectors-flowchart.js' {
  declare module.exports: $Exports<'jsplumb/src/connectors-flowchart'>;
}
declare module 'jsplumb/src/connectors-statemachine.js' {
  declare module.exports: $Exports<'jsplumb/src/connectors-statemachine'>;
}
declare module 'jsplumb/src/connectors-straight.js' {
  declare module.exports: $Exports<'jsplumb/src/connectors-straight'>;
}
declare module 'jsplumb/src/defaults.js' {
  declare module.exports: $Exports<'jsplumb/src/defaults'>;
}
declare module 'jsplumb/src/dom-adapter.js' {
  declare module.exports: $Exports<'jsplumb/src/dom-adapter'>;
}
declare module 'jsplumb/src/dom.jsPlumb.js' {
  declare module.exports: $Exports<'jsplumb/src/dom.jsPlumb'>;
}
declare module 'jsplumb/src/endpoint.js' {
  declare module.exports: $Exports<'jsplumb/src/endpoint'>;
}
declare module 'jsplumb/src/group.js' {
  declare module.exports: $Exports<'jsplumb/src/group'>;
}
declare module 'jsplumb/src/jsPlumb.js' {
  declare module.exports: $Exports<'jsplumb/src/jsPlumb'>;
}
declare module 'jsplumb/src/overlay-component.js' {
  declare module.exports: $Exports<'jsplumb/src/overlay-component'>;
}
declare module 'jsplumb/src/renderers-svg.js' {
  declare module.exports: $Exports<'jsplumb/src/renderers-svg'>;
}
declare module 'jsplumb/src/util.js' {
  declare module.exports: $Exports<'jsplumb/src/util'>;
}
declare module 'jsplumb/tests/bind-shim.js' {
  declare module.exports: $Exports<'jsplumb/tests/bind-shim'>;
}
declare module 'jsplumb/tests/endpoint-loadtest.js' {
  declare module.exports: $Exports<'jsplumb/tests/endpoint-loadtest'>;
}
declare module 'jsplumb/tests/experiments/connector-editors.js' {
  declare module.exports: $Exports<'jsplumb/tests/experiments/connector-editors'>;
}
declare module 'jsplumb/tests/experiments/npm/browserify-test.js' {
  declare module.exports: $Exports<'jsplumb/tests/experiments/npm/browserify-test'>;
}
declare module 'jsplumb/tests/experiments/npm/input.js' {
  declare module.exports: $Exports<'jsplumb/tests/experiments/npm/input'>;
}
declare module 'jsplumb/tests/experiments/overlays-guidelines.js' {
  declare module.exports: $Exports<'jsplumb/tests/experiments/overlays-guidelines'>;
}
declare module 'jsplumb/tests/jsPlumb-tests.js' {
  declare module.exports: $Exports<'jsplumb/tests/jsPlumb-tests'>;
}
declare module 'jsplumb/tests/loadtest.js' {
  declare module.exports: $Exports<'jsplumb/tests/loadtest'>;
}
declare module 'jsplumb/tests/makeSourceLoadTest.js' {
  declare module.exports: $Exports<'jsplumb/tests/makeSourceLoadTest'>;
}
declare module 'jsplumb/tests/miscellaneous/exampleConnector.js' {
  declare module.exports: $Exports<'jsplumb/tests/miscellaneous/exampleConnector'>;
}
declare module 'jsplumb/tests/miscellaneous/issue_106_test/js/EndPoints.js' {
  declare module.exports: $Exports<'jsplumb/tests/miscellaneous/issue_106_test/js/EndPoints'>;
}
declare module 'jsplumb/tests/miscellaneous/issue_106_test/js/jquery-ui-1.8.14.custom.min.js' {
  declare module.exports: $Exports<'jsplumb/tests/miscellaneous/issue_106_test/js/jquery-ui-1.8.14.custom.min'>;
}
declare module 'jsplumb/tests/miscellaneous/issue_106_test/js/jquery.jsPlumb-1.3.1-all.js' {
  declare module.exports: $Exports<'jsplumb/tests/miscellaneous/issue_106_test/js/jquery.jsPlumb-1.3.1-all'>;
}
declare module 'jsplumb/tests/miscellaneous/issue_106_test/js/jquery.min.js' {
  declare module.exports: $Exports<'jsplumb/tests/miscellaneous/issue_106_test/js/jquery.min'>;
}
declare module 'jsplumb/tests/miscellaneous/issue_106_test/js/util.js' {
  declare module.exports: $Exports<'jsplumb/tests/miscellaneous/issue_106_test/js/util'>;
}
declare module 'jsplumb/tests/miscellaneous/jquery.mockjax.js' {
  declare module.exports: $Exports<'jsplumb/tests/miscellaneous/jquery.mockjax'>;
}
declare module 'jsplumb/tests/miscellaneous/jQueryOffsetCSS3Scale.js' {
  declare module.exports: $Exports<'jsplumb/tests/miscellaneous/jQueryOffsetCSS3Scale'>;
}
declare module 'jsplumb/tests/miscellaneous/object-avoid.js' {
  declare module.exports: $Exports<'jsplumb/tests/miscellaneous/object-avoid'>;
}
declare module 'jsplumb/tests/miscellaneous/sprout-test.js' {
  declare module.exports: $Exports<'jsplumb/tests/miscellaneous/sprout-test'>;
}
declare module 'jsplumb/tests/miscellaneous/svg-sprout.js' {
  declare module.exports: $Exports<'jsplumb/tests/miscellaneous/svg-sprout'>;
}
declare module 'jsplumb/tests/qunit-1.11.0.js' {
  declare module.exports: $Exports<'jsplumb/tests/qunit-1.11.0'>;
}
declare module 'jsplumb/tests/test-support-dom.js' {
  declare module.exports: $Exports<'jsplumb/tests/test-support-dom'>;
}
